# Generated by Django 3.2.20 on 2024-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('roman', 'Roman'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('drama', 'Drama'), ('horror', 'Horror')], max_length=100)),
                ('length', models.PositiveIntegerField()),
                ('image_card', models.ImageField(upload_to='movie_image/')),
                ('image_cover', models.ImageField(upload_to='movie_image/')),
                ('video', models.FileField(upload_to='movie_video/')),
                ('movie_views', models.IntegerField(default=0)),
            ],
        ),
    ]
