# Generated by Django 3.2.20 on 2024-08-18 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
